[project]
name = "retinatrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7, <3.8"
dependencies = [
    "torch~=1.5.0"
]

[tool.setuptools.packages.find]
where = ["retinatrack"]
